Shopify/Models/CollectionS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shopify.Models
{
    public class CollectionS
    {
         
            public decimal id { get; set; }
            public string title { get; set; }
            public string handle { get; set; }
            public string vendor { get; set; }
            public string product_type { get; set; }
            public string published { get; set; }
        public CollectionS()
        {

        }
         
    }
}

Shopify/Controllers/CollectionsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shopify.Shopify;
using ShopifyAPIAdapterLibrary;

namespace Shopify.Controllers
{
    [ShopifyAuthorize]
    public class CollectionsController : Controller
    {
        ShopifyAPIClient _shopify;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            ShopifyAuthorizationState authState = ShopifyAuthorize.GetAuthorizationState(this.HttpContext);
            if (authState != null)
            {
                _shopify = new ShopifyAPIClient(authState, new JsonDataTranslator());
            }
        }

        public ActionResult Index()
        {
            // get all shopify blogs
            dynamic blogResponse = _shopify.Get("/admin/custom_collections.json");
            ViewBag.Collections = blogResponse.custom_collections;
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // From the shopify docs, this is the expected format
                //{
                //  "blog": {
                //    "title": "Apple main blog"
                //  }
                //}
                //so create the .NET equivalent of that
                dynamic blogData = new
                {
                    custom_collection = new
                    {
                        title = collection["Title"]
                    }
                };
                dynamic createBlogResponse = this._shopify.Post("/admin/custom_collections.json", blogData);

                //check response for errors

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                // handle the exception
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            dynamic blogData = this._shopify.Get(String.Format("/admin/custom_collections/{0}.json", id));

            ViewBag.blog = blogData.blog;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here
                dynamic blogData = new
                {
                    blog = new
                    {
                        title = collection["Title"]
                    }
                };
                dynamic updateBlogResponse = this._shopify.Put(String.Format("/admin/custom_collections/{0}.json", id), blogData);

                //TODO: Check the repsponse and make sure the action you wanted to happen happened

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            dynamic blogData = this._shopify.Get(String.Format("/admin/custom_collections/{0}.json", id));

            ViewBag.blog = blogData.blog;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                dynamic deleteBlogResponse = this._shopify.Delete(String.Format("/admin/custom_collections/{0}.json", id));

                //TODO: Check the repsponse and make sure the action you wanted to happen happened

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Shopify/Views/Collections/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Blog</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
		<label for="title">Title</label>
		<input type="text" id="title" name="title" class="form-text" value="" />
	</fieldset>
    
	<fieldset class="form-actions">
		<input type="submit" value="Submit" />
	</fieldset>
}

<p>@Html.ActionLink("Back to List", "Index")</p>

Shopify/Views/Collections/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    var id = ViewBag.blog.id;
    var title = ViewBag.blog.title;
}

<h2>Delete Blog</h2>
@using (Html.BeginForm(new { id = id }))
{
    @Html.AntiForgeryToken()

<p>Are you sure you want to delete this blog? <input type="submit" value="Delete" /></p>
<p>Title: @title</p>

<p>@Html.ActionLink("Back to List", "Index")</p>

    
}

Shopify/Views/Collections/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    var title = ViewBag.blog.title;
    var id = ViewBag.blog.id;
}

<h2>Edit Blog</h2>


@using (Html.BeginForm(new { id = id }))
{
    @Html.AntiForgeryToken()

    <fieldset>
		<label for="title">Title</label>
		<input type="text" id="title" name="title" class="form-text" value="@title" />
	</fieldset>
    
	<fieldset class="form-actions">
		<input type="submit" value="Submit" />
	</fieldset>
}


<p>@Html.ActionLink("Back to List", "Index")</p>

Shopify/Views/Collections/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Shopify Collections</h2> 
@if (ViewBag.Collections == null || ViewBag.Collections.Count == 0)
{
 
    <p>There are no blogs yet.</p>
} else {
    <table>
        <thead>
            <tr>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
                <th>Title</th>
            </tr>
        </thead>
        <tbody>
    @foreach (var blog in ViewBag.Collections)
    {
            <tr>
                <td>@Html.ActionLink("Edit", "Edit",new { id = blog.id })</td>
                <td>@Html.ActionLink("Delete", "Delete",new { id = blog.id })</td>
                <td>@blog.title</td>
            </tr>
    }
        </tbody>
    </table>
}

<p>@Html.ActionLink("Add Collections", "Create", "Collections")</p>